### ISSUE TITLE
It seems like this no longer compiles again?

### ISSUE THREAD

**Issue by shuhaowu** [domoritz/line-density-rust#3]
Something is wrong with imageproc, but I don't know enough rust to fix this:

```
rror[E0034]: multiple applicable items in scope
   --> /Users/shuhao/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.16.0/src/hog.rs:452:33
    |
452 |             let intensity = u8::clamp(hist[bucket]);
    |                                 ^^^^^ multiple `clamp` found
    |
    = note: candidate #1 is defined in an impl of the trait `Ord` for the type `u8`
note: candidate #2 is defined in the trait `Clamp`
   --> /Users/shuhao/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.16.0/src/definitions.rs:68:5
    |
68  |     fn clamp(x: T) -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #1
    |
452 |             let intensity = Ord::clamp(hist[bucket]);
    |                             ^^^^^^^^^^
help: disambiguate the associated function for candidate #2
    |
452 |             let intensity = Clamp::clamp(hist[bucket]);
    |                             ^^^^^^^^^^^^

error[E0034]: multiple applicable items in scope
   --> /Users/shuhao/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.16.0/src/hog.rs:456:33
    |
456 |             let intensity = u8::clamp(hist[bucket]);
    |                                 ^^^^^ multiple `clamp` found
    |
    = note: candidate #1 is defined in an impl of the trait `Ord` for the type `u8`
note: candidate #2 is defined in the trait `Clamp`
   --> /Users/shuhao/.cargo/registry/src/github.com-1ecc6299db9ec823/imageproc-0.16.0/src/definitions.rs:68:5
    |
68  |     fn clamp(x: T) -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for candidate #1
    |
456 |             let intensity = Ord::clamp(hist[bucket]);
    |                             ^^^^^^^^^^
help: disambiguate the associated function for candidate #2
    |
456 |             let intensity = Clamp::clamp(hist[bucket]);
    |                             ^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0034`.
error: could not compile `imageproc````

**Comment by domoritz** [comment]
I fixed it but I'm sure you can write a better implementation than what I hacked together here.

**Comment by shuhaowu** [comment]
Thank you for the quick fix! I'm already considering giving that an attempt, although I need to understand a bit more on exactly how the plot is generated. I'll give it a try in the next few days if time permits.

**Comment by domoritz** [comment]
Have a look at the paper: https://arxiv.org/abs/1808.06019

**Comment by shuhaowu** [comment]
A minor update and a question... I gave an attempt at my own implementation that normalizes the data (both x and y) so it fits into the image. I realized that my approach with OpenCV doesn't quite work as I needed to draw lines starting from non-integer coordinates, which is not possible. Further, since i have about 20-100 datapoints per pixel (depending on how big the output image is supposed to be), it is a challenge to compute it on the CPU, and I'm not familiar enough with GPU programming for now to implement anything quickly. Unfortunately I'm also running out of time, so at least in the next bit I won't have time to try this again..

That said, as I'm going through this exercise, I realize I don't understand the exact differences between the line density chart, and a simple scatter plot heatmap. This is mentioned in the paper: 

> This definition is more subtle than for a scatterplot heatmap: the data that underlies line charts is not usually recorded at every point. Rather, a line chart connects a set of time/value pairs; the technique must count how many different series lines passthrough each bin.

I'm curious to know if you know if any comparison has been made with the two techniques? My naive understanding is that it would be _almost_ the same thing, as the density of points and density of line segments should converge if there are a lot of data points. I can see that scatterplot heatmaps will have a harder time capturing extreme line series that traverse through areas outside the normal range of values observed (B in figure 10 of your paper). Line density plots may also put more emphasis on lines that have a larger slope (?) although I'm not sure if that interpretation is correct nor relevant. If this interpretation is true, perhaps a scatterplot heatmap is "good enough" in most situations? Am I missing something?

As an example of the scatter plot heatmap, here's an example data that I plotted with the [`hexbin`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hexbin.html) functionality of matplotlib. There appears to be trends that can be observed, similar to the line density stock price. 

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/338100/126679366-79d14966-d74d-4f17-bdce-009acbd521b8.png">

**Comment by shuhaowu** [comment]
Actually, thinking about this a bit more:

Another place where the line density plot would be better is if the interval between multiple data points are big (I think this is also mentioned in the paper), making it more accurate to the scatterplot heatmap approach. That said, we might be able to use the scatterplot heat map approach if we artificially added interpolated points between the real data points collected, prior to feeding it into hexbin. Adding these points kind of approximate the line used in the line density plot, although I'm not sure how equivalent they would be. It would, however be less work to implement as  existing library functions already exists for these operations.

Again, not sure if I missed something.

**Comment by domoritz** [comment]
You toughed on most of the important differences.

1. A time series may be sampled at arbitrary intervals so just making a scatterplot off of data for a time series may be misleading. This problem goes away when you sample at regular (and the same for all time series) intervals.
2. A line is continuous so if you don't have high enough resolution in your data, you can have gaps in a heatmap if you just use points.
3. If points are sampled along the line (rather than at regular intervals along the time axis), then there is more data for steep sections, which can lead to artifacts (we have a figure that shows its in the paper.

Given these three observations, I think that a heatmap of time series data with a) high enough resolution and b) regular samples along the time axis should give you almost the same result as the line density chart. I have to think a bit more to confirm this but this is my intuition right now. And yes, computing a simple heatmap for sampled points should be a lot easier/faster but you have to ensure a) and b).

Does that make sense?

> Line density plots may also put more emphasis on lines that have a larger slope (?

That's exactly what the normalization step avoids! 

Really cool looking plot, btw. I don't think you even need hexbins but regular rectangular bins should work just as well for the resolution you have.

**Comment by shuhaowu** [comment]
Thanks for conversing with me here. I agree with everything you mentioned. I forgot about normalization for a second when I wrote the part about the slope emphasis 😅 , but just to develop that idea a bit further: I think for point 3, if points are sampled along the line not at uniform delta x (horizontal axis, as shown in Fig 5 of your paper), but uniform delta s (where s is the line curve length), then the result of the scatter heat map might be very close to the line density plot with normalization. This needs validation/comparison, of course. 

That said, sometimes it could be helpful to find locations where large scope occurs (especially in bulk), but that is perhaps beyond the scope of the density line approach. 

> Really cool looking plot, btw. I don't think you even need hexbins but regular rectangular bins should work just as well for the resolution you have.

Thanks! As a note about resolution: my data is indeed regular. The plot I've shown above is generated using about 10,000 points sampled regularly with about 1,000 series, which roughly works out to about 10M data points. Using a 2000x1000 px image as an approximation, each vertical column of pixels needs to represent 5 data points if used without binning. One thing that is hard to do is to choose the "right" bin size. I suppose one technique you can use is to choose different bin sizes and visually compare to see if your plot has "converged" or not, to find the optimal bin size that doesn't have some potentially misleading artifacts one them.

Not sure if there's anything here worth writing more publicly about, but certainly it has been very interesting and I thank you once again for walking me through this.

**Comment by domoritz** [comment]
> I think for point 3, if points are sampled along the line not at uniform delta x (horizontal axis, as shown in Fig 5 of your paper), but uniform delta s (where s is the line curve length), then the result of the scatter heat map might be very close to the line density plot with normalization. This needs validation/comparison, of course.

I think that would be almost the same as the heatmap WITHOUT normalization. 

> That said, sometimes it could be helpful to find locations where large scope occurs (especially in bulk)

Yes, for a single line, but not in aggregate as density could then come from either many lines or some steep lines and it's impossible for a viewer to tell.

**Comment by shuhaowu** [comment]
> I think that would be almost the same as the heatmap WITHOUT normalization.

Hmm. You're likely right. It's hard for me to compare the two approaches in my head at this point. I'll give this approach a few more datasets and see what happens.
